# Generated by Django 2.1.7 on 2019-03-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('karma', models.IntegerField(blank=True, null=True)),
                ('subreddit', models.CharField(blank=True, max_length=500, null=True)),
                ('submission_link_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('submission_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'reddit_posts',
            },
        ),
    ]
